Adding unit tests
Mastercard/oauth1-signer-ruby pull request #7
Opened 2019-05-08 14:44 UTC by danny-gallagher

- Adding unit tests

2019-05-08 14:44 UTC, danny-gallagher commented
@jaaufauvre Please review when you get a chance

2019-05-09 18:25 UTC, jaaufauvre requested changes

2019-05-09 18:25 UTC, jaaufauvre commented on tests/test_oauth_extract_query_params.rb
> +  def test_extract_query_params_should_support_rfc_example_when_uri_created_from_uri_string
@danny-gallagher: this test appears twice

2019-05-09 18:25 UTC, jaaufauvre commented on tests/test_get_signature_base_string.rb
> +      assert(sbs.include? "GET&https%3A%2F%2Fexample.com&param%3Dtoken1%3Atoken2");
Nice one :)

2019-05-13 09:44 UTC, jaaufauvre approved these changes

2019-05-13 09:44 UTC, merged